---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder-db
  namespace: flux-system
spec:
  prune: true
  interval: 5m
  # dependsOn:
  #   - name: longhorn
  path: "./apps/coder-db"
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: coder-db-postgresql
      namespace: coder
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder
  namespace: flux-system
spec:
  prune: true
  interval: 5m
  # Speed up iteration
  # dependsOn:
  #   - name: coder-db
  path: "./apps/coder"
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      CODER_HOST: coder.uk.sharing.io
      CODER_ACCESS_URL: https://coder.uk.sharing.io
      CODER_WILDCARD_DOMAIN: "uk.sharing.io"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tunneld
  namespace: flux-system
spec:
  prune: true
  interval: 5m
  # Speed up iteration
  # dependsOn:
  #   - name: coder-db
  path: "./apps/tunneld"
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      TUNNEL_ACCESS_URL: https://try.sharing.io
      TUNNEL_WILDCARD_DOMAIN: "try.sharing.io"
