apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: minio
  name: minio-sftp
  namespace: minio
# We might be able to run this on port 22 if we used another IP
# And DNS name
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  ports:
    - name: sftp-minio
      port: 8022
      protocol: TCP
      targetPort: 8022
  externalIPs:
    - 145.40.113.209
  selector:
    v1.min.io/tenant: minio
  # clusterIP: None
  # clusterIPs:
  #   - None
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ipFamilies:
    - IPv4
