apiVersion: v1
data:
    config.env: ENC[AES256_GCM,data:DuqxfYJNhux02X/v+oVWa5uIQ529LsCJBkKgkJkWxJGc9u97NeL5y2kPTva3SQj73j5yobJZFjOPAeYxzLqW7GCQv0WbUNjLoHNAhly3D6y275PVsfkkoA3zDzs/S3C4YHVwpTKR5nrgpsbk/n/V/+iy6vLne21e9kIMO8ddRwxViBkIGMdfj+eFrVavZfVffQzuDAK6q3JjIgR0HbuUlm0sNtF8fTI5xLlTl5gk4kk9UNDJCmh2B/dsPy+xTCnQCP9vgepLz8MX29k+29mEjJtlqGHYVTBWWv5wUli4kumTor5o9iHXS7pZKiqiuHzDu6qAyvlbUsRdfjH5LAg0MKiutIvPU88Z8+UY3UwCVI0Ruy7j4FDK3qI525ggTdRLdRMutk8ti2MVGyt11AOiIyxazxau2evRXNc6f998r/LwETqm1cBo2qEGgYr2HzHdrznEW5lU3Isfmw5XwB7LFOhLVt2IAiawB9LqmKhE/q4rP+f0fpS5fcDFlH/TXGbb4g4c70NoLGIAIL0U8WCajAjGdVDYdLt2G8tzjq0A2DN10XS1mXAy7nAvZFQ=,iv:JfAN2V9O8oroE7Uytb/gxhMVfWREfZaTTpN/QuANpAc=,tag:j9OkKjO6zWozu38UAAVrwg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-env-config
    namespace: minio
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-22T13:35:35Z"
    mac: ENC[AES256_GCM,data:We7m9lKT48vU9oa4YJJtpm0jqHjD6p2KOjfWxQEvXbjQlj+DXMO5uFo8bHw/vagbgkpGZOo41AhCAWW7uhljzRewLFaBtVWcGUV7Wc0TeNNa4UY2xkEMJTdXmV+TVBxb0aIxtUa+yIKIopeKilG4ty4hk9vy3Xj1hdA2MkhGIho=,iv:AYtyCC6jCqf502HZqjXkK6CUETmtxpQkIyx/+XzCmcc=,tag:+CI5Mq6cx6aN1w38BHZcyA==,type:str]
    pgp:
        - created_at: "2023-08-22T13:35:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1CUw1M+w4b+ARAAo5e1StuSiRiCfXJ6u4JXQev79f6nM4Bwpb1Kr9uDzyFk
            ICQHEu3LiCjHToYMG2ACHPV5fQZPxz0h9r/fCO3JoEqGxPyQcp0wXbJanEIantbf
            w81V7CPvRDFn7/NswvEoVo/cZSuMNN/OFIJye3roGI5kKqb9cqfNrN4vnWVfZqwm
            hTmTXjayKKZ0glGsYiwM143iLZq9B0J8ZB0ti4WibkiW0QVOMO/NJissVfnK8ZyI
            kkmLNr+J1IR4qwdIfap0YHvp+GRgm9KD/GaYtbUOxw3rTnumLyzvrW/LZzbEbAjA
            ohk0nS07PXXG95Xwzeaw7Tg9L8iM2eVeT63Qkd8AYodI9z2F/pOa3uv94WjCHxRT
            Oc4RH2VINDaIumTFTxOSAP4SmMPlu+EWODCkDKPOAZi8cu2YjwokGlkh/oDDdAY2
            ePCLz3VAt/t0hWYHp5XjjQcfLBpdOiOhNnDI2ZgsuXxQgKISv1bn/VgzPqUDqsLj
            Gk9JxL569zxn8Cj47jjJc21OBlStZgx40CTshhoq0xT85ZuU+d4lv079DuP3P0PW
            Vt2YvrcZpwzK1K8qFtYDns0Wp52m7++aHvQwPMH+10OMlNsPMVkr1pbzUqxWCDgL
            RkMnXo2JAh+73hG3kE41Aaf+09Jippu72qW0CNN+jpeqdPV/9myP3dw1Bt3lQADU
            aAEJAhCCq9jobVMs8nuTGXCiJSRmbvpjR1DVwJGxzkquzGXtbvoC7kAVDrAXbsR2
            M2XGSV5vzJuRnUPdRDC+gZPlw1/N9EeCm1vUETow+c9Tm0bYSNHp8STHMWd7R9pM
            7peFhb62n2KO
            =Llqa
            -----END PGP MESSAGE-----
          fp: ECD5E68E3550DD7990346DBE2905C53630D2C990
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
