---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns
  namespace: flux-system
spec:
  # It does depend on at creation
  # dependsOn:
  #   - name: secrets
  interval: 5m
  path: "./infrastructure/apps/powerdns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substitute:
  #     MINIO_INGRESS_HOST: minio-operator.uk.cloudnative.coop
