---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns
  namespace: powerdns
spec:
  interval: 5m
  path: "./infrastructure/apps/powerdns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substitute:
  #     MINIO_INGRESS_HOST: minio-operator.uk.cloudnative.coop
