# certificate resource yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: try
  namespace: coder
spec:
  issuerRef:
    name: letsencrypt-pdns
    group: cert-manager.io
    kind: ClusterIssuer
  commonName: "*.${TUNNEL_WILDCARD_DOMAIN=try.ii.nz}"
  secretName: try-tls
  dnsNames:
    - "${TUNNEL_WILDCARD_DOMAIN=try.ii.nz}"
    - "*.${TUNNEL_WILDCARD_DOMAIN=try.ii.nz}"
