---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: abcs.news-cert
  namespace: ghost
spec:
  secretName: abcs.news-tls
  dnsNames:
    - "abcs.news"
    - "*.abcs.news"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
