apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # These two are create by the ./clusters/X/secrets kustomization
  # - namespace.yaml
  # - passwords.yaml
  # Manually copied over the cert for now, we have two months to get
  # a cert issuer to re-issue
  # - cert.yaml
  - ingress.yaml
  - service-accounts.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  # I restored these from a longhorn backup
  # - pvc.yaml
