---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ghost-mysql
  namespace: ghost
secrets:
  - name: ghost-passwords
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ghost
  namespace: ghost
