---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  targetNamespace: harbor
  releaseName: harbor
  storageNamespace: flux-system
  # We install the namespace with the secret
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.12.4" # Current as of August 20, 2023
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 12h
  # Quite a refactor three months ago: https://github.com/goauthentik/helm/pull/163
  # https://artifacthub.io/packages/helm/goauthentik/authentik#values
  # # -- see configuration options at https://goauthentik.io/docs/installation/configuration/
  #  postgresql-password: A
  #  postgresql-postgres-password: B
  values:
    # OIDC might need to be in CONFIG_OVERWRITE_JSON which might be in 1.13.0
    # The name of secret where admin password can be found.
    # existingSecretAdminPassword: harbor
    # The name of the key in the secret where to find harbor admin password Harbor
    # existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    tls:
      enable: true
      certSource: none
    externalURL: https://harbor.uk.cloudnative.coop
    expose:
      ingress:
        className: nginx
        hosts:
          core: harbor.uk.cloudnative.coop
          notary: notary.uk.cloudnative.coop
