---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder-db
  namespace: flux-system
spec:
  prune: true
  interval: 5m
  dependsOn:
    - name: longhorn
  path: "./apps/coder-db"
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: coder-db-postgresql
      namespace: coder
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder
  namespace: flux-system
spec:
  prune: true
  interval: 5m
  dependsOn:
    - name: coder-db
  path: "./apps/coder"
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      CODER_HOST: space.cloudnative.nz
      CODER_ACCESS_URL: https://space.cloudnative.nz
      CODER_WILDCARD_DOMAIN: "cloudnative.nz"
      TSIG_NAMESERVER: 123.153.176.253
      TSIG_KEYNAME: cloudnative.nz
      TSIG_ALGORITHM: HMACSHA256
