---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/controllers/minio-operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      MINIO_INGRESS_HOST: minio-operator.cloudnative.nz
