apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:gwDuWdTrdhQ3nok/jcNd8kQsgdxStwNEPE0J1Q==,iv:Xq+8bUU544ojXrxwfUeqeEZJy/qffBCB4J5TYIJMR9w=,tag:VvJ5zYraYOTfulUdiUOu8A==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:lduk05w7UHUU/pxVLtzhOhBhBHPYXU2/vj7WYsQPocqbqj336viDb++yTIzsxUfrIFPrjn19IY0=,iv:un8kqbgwZKONOAEDvZwMFviW59sl+VXHq/0TuKZs8bY=,tag:4wFtbfVcbbYrN9HdKD56rQ==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:NT/MW9BmcJu5R/LwWxKEkCJwEBJmYiUgM33gDQ==,iv:S5b64+0hFE46ou9vHSzX1DgGb5v3S17ezpqv0yuhd1k=,tag:NL5wydV9o+cJGEBGOHpU9w==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:2RDNJLKffEj0igtsa39opT31rJipgWNJIZWNxJVSIKU6Q5NxzOErOW1ofsz7kvcV1R7KzRIwh+4=,iv:qquduTecXrOpwGnw2K7j5+BHLCS/zRsPjKUs1AXjPrE=,tag:adqf71/RWKmbFZiYgLagpw==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:afFaO7EF7Sq3VW2SmoJckKxKCxzggwLUcFRvshXUSgDaxzUb9Snp72W0aQl8082GJVjsjfsJ2gk=,iv:pyEaKAtX5kmYLzY+Bl9aHnkxsFvSg95ftm+u4kDYpgQ=,tag:OqVaxsD14GYLv9hLxLG8Ow==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1ymm/K7CNqAtri1U3F9FrjfUj3mPbBcmJFJGWhR6oJ71Tw5dFbI4AzD7z+vHTn5n2nLUb042JOJZZSK87CtFAZoulIP7dqNclnVHuMcntQZ1no+Qm096062MYE3AKo+6al89SG0uxL0W8/HTAEK0OuAhlnRHjyLJBrDiwLuAhQuOl/BhjrgUgoy/KzUA8TbotrtdBvLNY5BJdElRqf8NPsJZB7DVCp4SyxIvmA==,iv:cID6S/PDODn4r7savD2q8jjMIBghi1Y6uxKmeU42U7o=,tag:+kT0Ha5ckXpwY8athOMyTw==,type:str]
    CODER_PASSWORD: ENC[AES256_GCM,data:Mx2HQahRc8oi/7eGwHiq3w==,iv:EeyDa+wgL5f7Q4obvgT79sGcUUHBNAY1M20MG7BZRgM=,tag:SGYBwHnIST/UdJe/CSZXvQ==,type:str]
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:Te8mxvcMIVqzyUQzC8nT5XpuRpT/WrUn3ZmqOUY1tLSZf2vrAXCIl/njjr5z/Th6CJGF/bhfb/QjP4pxMfr7EE9n2EUlh5ig9zVjBtnINT/Rxm+LtDNCLoWx+5yjwnbrCnJhf0COTTdCE3vbbQXsy2hIpp5A8jyH0KbXs+xPca89ZVX8MIw1nwEBfxg=,iv:dhCCJKYBpLkBVGDyp7+2nLbLssB+ZEB9JPn4iRtLQgU=,tag:9VU4innBHOg5/HLTkuhUqg==,type:str]
    CODER_USERNAME: ENC[AES256_GCM,data:bRp7wMlENFU=,iv:mSXaLMiFOVuTZGTfuSZkvoXqzJh/LOUC8HRJrvnmuxE=,tag:8JCaN8lDZRrYPmNF0hgmBw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:fWSgYbXlPKRol0oPxnHYGs5MhJH7dfKYz+ex2keC2w4aWOZEz+L5XVnzw4kNtAeq0uCrZ6cVpLL7vk9nh+vNIvpRFeZ8NM5fTJoZzbuMI30o59WcySs4hD1aKJtFW5pLPBqXAE5avqCffawl8yZJiKvk9IIvmQHYOxka6g==,iv:ZvWhC1LznOyTfn6Qd1/acz+RQRxrQ3wntJ0tbVlNKN4=,tag:aGiOBKJntIMm+ry9GGum6Q==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:3Ii2EaDGoluL52Xgmu274tD4vo9BZwaAqwuqcee+YvqZXF6DPfZGQY2y5Bg=,iv:NcS2GwMOVvq6SN/0Ljb22sr0sU59OBgCPHpf3aDGLHE=,tag:ftcIo6GnfrSCi085zucq5g==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:9RAIhamVKxc2WDhQl2ji60Au18Gef02G7pk6WQ==,iv:KMwuZRLq3TjpfHedk8c+JbqtzLQZWc/CnKPnOIl+aUw=,tag:CDj3HpR+ckjVGBFG5iYyvA==,type:str]
    PDNS_TSIG_KEY: ENC[AES256_GCM,data:JWeLFHT54/q4PORcLrhKtd2eLe9GeNYbO5TRhocVJEu+g5bIAC04hJNMLgvYgZvB4aztgQL9Y8HFFRTE9q4UmKVgVLt/po+a0GjuQXbTpQThGc3XrTdiO/4E7vAwqsq9xCgIIX0F+eGAqsaHG3NezoydPazMrtez,iv:VbWtXviIALOd6pvhXVMNPd4189l5B9KCpbWloM6nKu8=,tag:d7IjXXmHpeXopWDM6brnWw==,type:str]
    TUNNELD_WIREGUARD_KEY: ENC[AES256_GCM,data:s6DPeKLpLZ3Rijd/2Vl6DqszFyIS0PgfD+IxBpqUFe9pH9I9EG19FwIhtKgts9R8Ci3+Nf6z5KFC5wCs,iv:TPCs7y6TVSezolzdoxBNMAxIecp4otYNcJbKBLoxHJQ=,tag:uFTRt3knb/YoUVfijeV2Jw==,type:str]
    password: ENC[AES256_GCM,data:ODFCyZlbtc1K+89q/PSYRw==,iv:SVN3tSn/P6dU4U7PRbiVSzbpD+vvjGr67IAkqU7pNEA=,tag:W/51wkP3VojuQOd+wsalMQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:gSz52SgIgbI+NKLpo+uuLQ==,iv:bWXV5TAvpsxK9dQN8kYGpGosRe1wiqSU4IH4ofKhak4=,tag:qwF9BOsErz6Wl3tcFo7v4w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-01T23:19:10Z"
    mac: ENC[AES256_GCM,data:Rb/QLZWsr+hBB6Agz+01PsmI3NhUyrouKYNqvEKs7eT2pC2yHuHdZOGtKjcT59+N6t69/dhcLbpdDE0EJVdRqeEpW/9zFqXY4cyRLcFr8HZG+gtvdzbdMfW9vpz45GpSX19BDVdCt+iQrQrECf8oMY4ojcpqFGaPfILmsNJgDMU=,iv:q1Dh1/lwl/iOC2oatAXykI4VgfHvwwEsEGsXwCZvjRY=,tag:V57i6qDpbgkimm5TRzi4Kw==,type:str]
    pgp:
        - created_at: "2023-09-01T23:19:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5yBPHua1+foAQ/+JFvWEjb4MZZZBvALi6CCJ9/hZi+kyewYVHLfmjPFZgdh
            zQNGSoXzrGa8ZmXo59kJ2IGX+XCu5P5yh3w/lYwBn63lYWW5FRg/htae2KciFbbg
            DCS35oElUgbE5573LG5arkp0QcKriMmyO/BSfn4SAqXyH+9jTnr2Ixz/XP3Co16E
            ofTGgY4I3cqYOCn7+OPARgHNPftfceGOjhAHfMmApAbP6QolSK8hCZDtwtITyw2I
            /vp9K/orloWykAOVM4DeQprNN2uOgbzfKmIkIrheeiESZ+t2zxy8r0JEiI8RJyYa
            p8kyTkZUuDTHVv4jXBrfXJOp/ypQCn84Bo4JR40DCqyc/r72YQPLZXMKLItjDue3
            7UazWFo3pVZVUiWI6mc7bU7vhGE4KXunh6EHnu8++frM3DbE47fR0w0/Hb2nEMLO
            7Hfbwewr1OkA/X36+DSn4aA0/Dx8NO1hFytH3Of7Of073n5/BnmZxpW1ZOPG3eHE
            aQEHN3YCtJPi2jKIhPp9Y3vR2oFyWQau0IWwXhkXiVqYy98Ye/E32LQB1tSL+67O
            JGlNK08Iz5iUL8R8arcIv+AOJuVt+7mIo67FZ+/SRlBSSzMrxgzEkVl8QKGCm2AU
            AkTjrHOmjAKEym3RepWL+Ev3q7l1IebuQIdOS03UkxnJyY1y1evVsYazdmO/TFjU
            ZgEJAhC5xj7kaD4OBCHSSctb2j4/09Lwn9PUaa6cd5Czg92BlTUCyqn3XCrRq1FT
            umCRf8HRt2N9VHUvX4CScEoxJXzgs1BGK4Txk00H1ouPH5CTaHSQGbwHpDFdrr1a
            vPEUGS8OPw==
            =WXSj
            -----END PGP MESSAGE-----
          fp: 6CFB156EEFE7417E2567D5FD37732CFA004DC229
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
