ingress:
  host: k8s-heyste.cloudnative.nz
syncer:
  kubeConfigContextName: "k8s-heyste"
  extraArgs:
    - --tls-san=k8s-heyste.cloudnative.nz
    - --out-kube-config-server=https://k8s-heyste.cloudnative.nz
    - --out-kube-config-secret=kubeconfig-heyste
api:
  volumes:
    - name: audit
      configMap:
        name: k8s-audit
        items:
          - key: sink.yaml
            path: sink.yaml
          - key: policy.yaml
            path: policy.yaml
